replicaCount: 1

image:
  repository: ghcr.io/3-istor/qcm
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  NODE_ENV: "production"
  NEXT_PUBLIC_APP_URL: "https://qcm.3istor.com"
  KEYCLOAK_CLIENT_ID: "qcm"
  KEYCLOAK_ISSUER: "https://auth.3istor.com/realms/3istor"

existingSecret: "qcm-secrets"
